name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9.22']

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: tradingbot_env
          auto-activate-base: false

      - name: Install project dependencies
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install pre-commit

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

      - name: Run backend tests
        run: |
          pytest backend/tests --maxfail=1 --disable-warnings --verbose --junitxml=test_results/backend-test-results.xml

      - name: Install frontend dependencies
        run: |
          npm install
          npm install --save-dev eslint prettier @typescript-eslint/parser @typescript-eslint/eslint-plugin

      - name: Run frontend linting
        run: |
          npm run lint
          npm run format:check

      - name: Run frontend tests
        run: |
          npm test

      - name: Run linting
        run: |
          flake8 backend/
          black --check backend/

      - name: Debug artifact paths
        run: |
          echo "Arbetskatalog:"
          pwd
          echo "Alla filer och mappar:"
          ls -R

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            test_results/
            backend/tests/coverage.xml
            frontend/coverage/
